### ISSUE TITLE
XML namespaces

### ISSUE THREAD

**Issue by goevexx** [jankstar/xrechnung-go#1]
Is this package in use? I wonder how one handles the issue with namespaces, which are not presents marshalling the Invoice2 struct. The structs xml.Name in any struct possibly overrides the tag given by the struct holding struct, which has a namespace in it.
E.g.  Invoice2 has a field AccountCustomerParty which holds AccountCustomerParty with namespace `urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2` in it's tag. The struct type AccountCustomerParty has  the field Name of type xml.Name and an extra tag given. So having an Invoice2 struct value holding a AccountCustomerParty value doesn't have a namespace because it was overriden by xml.Name, I assume. 
Even in the case of the namespace is given in tag of xml.Name it landed in `xmlns="..."` attribute instead as prefix colon notation due to different issues you can find in golang/go. The institute we as company want to engage with validates the output of marshalling wrong.
Have you experienced issues with those namespaces and in case you did how do you handle it?

**Comment by jankstar** [comment]
I have only tested the function in the library.
Do you mean "AccountingCustomerParty"?

With the xml.Name notation, the spaces are mapped individually - so this is done for all recursive non-primitive types of the struture. 
I generated the structure definition from the XSD specification and then manually adjusted it to make the mapping work. 

There is a sample file "UBL-Invoice-2.1-Example.xml" with this data at the link. Exactly this file is the test and I just started this, the data of the structure is determined without errors.

I have processed only the test data with the library.

**Comment by goevexx** [comment]
> I have only tested the function in the library. Do you mean "AccountingCustomerParty"?
> 
> With the xml.Name notation, the spaces are mapped individually - so this is done for all recursive non-primitive types of the struture. I generated the structure definition from the XSD specification and then manually adjusted it to make the mapping work.
> 
> There is a sample file "UBL-Invoice-2.1-Example.xml" with this data at the link. Exactly this file is the test and I just started this, the data of the structure is determined without errors.
> 
> I have processed only the test data with the library.

Yes, that's what I mean.
Well, in case I wanted to marshal `Invoice2` with `encoding/xml` to xml, it didn't output any namespace despite expectations. Using `github.com/alexrsagen/go-libxml` instead outputs xml namespaces - not in the wanted format `<NS:TAG>` but with `xmlns` attribute, which seems to be enough. I've also adjusted the order of some fields in my fork to make the [validator](https://github.com/itplr-kosit/validator) not throw a validation error, which is quite odd as it's xml validation seems to base on xml tags order.
